/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./templates/*.html",
    "./templates/**/*.html",
    "./templates/**/**/*.html",
    "./custom_account/templates/*.html",
    "./project/templates/*.html",
    "./job_post/templates/*.html",
    "./search_and_filter/templates/*.html",
    "./search_and_filter/templates/**/*.html",
  ],
  safelist: [
    "hidden",
    "lg:mt-0",
    "bg-aliceblue",
    "text-primary",
    "input",
    "input-bordered",
    "input-secondary",
    "w-full",
    "toggle",
    "toggle-secondary",
    "block",
    "text-sm",
    "font-medium",
    "text-gray-700",
    "file-input",
    "file-input-bordered",
    "file-input-secondary",
    "file-input-primary",
    "mt-3",
    "textarea",
    "textarea-bordered",
    "textarea-secondary",
    "bg-neutral",
    "text-neutral",
    "border-neutral",
    "justify-center",
    "items-center",
    "mr-1",
    "py-2",
    "px-5",
    "rounded-md",
    "bordered",
    "border-primary",
    "border-2",
    "group-hover:border-secondary",
    "cursor-pointer",
    "feather",
    "feather-x",
    "rounded-full",
    "w-3",
    "h-3",
    "ml-2",
    "lg:w-[calc(32%-2px)]",
    "h-48",
    "h-64",
    "h-72",
    "badge",
    "badge-primary",
    "alert-info",
    "alert-info",
    "alert-success",
    "alert-warning",
    "alert-error",
  ],
  theme: {
    extend: {
      container: {
        center: true,
        DEFAULT: "1em",
        sm: ".5em",
      },
      colors: {
        aliceblue: "#f4f9ff",
      },
      fontFamily: {
        hind: ["Hind", "sans-serif"],
        martel: ["Martel Sans", "sans-serif"],
        maven: ["Maven Pro", "sans-serif"],
      },
      screens: {
        sm: "320px",
        md: "728px",
        lg: "984px",
        xl: "1240px",
        "2xl": "1496px",
      },
    },
  },
  daisyui: {
    themes: [
      {
        "stackportfolio-default-theme": {
          primary: "#0166ff",
          secondary: "#131e32",
          accent: "#1fb2a6",
          neutral: "#333333",
          "base-100": "#fcfcfd",
          info: "#3abff8",
          success: "#36d399",
          warning: "#fbbd23",
          error: "#f87272",
        },
      },
    ],
  },
  plugins: [require("@tailwindcss/typography"), require("daisyui")],
};
