# Generated by Django 3.2.22 on 2023-11-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_location_type', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worklocationtype',
            old_name='work_location_type',
            new_name='name',
        ),
    ]
