# Generated by Django 3.2.22 on 2023-11-10 20:37

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('github_repo_url', models.URLField(max_length=255)),
                ('deployed_url', models.URLField(max_length=255)),
                ('project_active', models.BooleanField(default=True)),
                ('project_description', models.TextField()),
                ('project_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('project_view_count', models.IntegerField(default=0)),
                ('project_slug', models.SlugField(blank=True, null=True)),
                ('project_date_created', models.DateTimeField(auto_now_add=True)),
                ('project_date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
