# Generated by Django 3.2.22 on 2023-11-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
        ('project', '0005_alter_project_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(
                blank=True,
                related_name='projects',
                to='technology.Tech'),
        ),
    ]
