# Generated by Django 3.2.22 on 2023-11-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20231117_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='migration handle 1', max_length=100),
            preserve_default=False,
        ),
    ]
