# Generated by Django 4.2 on 2024-03-29 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0012_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributor',
            field=models.ManyToManyField(related_name='project_contrib', to=settings.AUTH_USER_MODEL),
        ),
    ]
