# Generated by Django 4.2 on 2024-03-29 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0013_project_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contributor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
