# Generated by Django 4.2 on 2024-03-30 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_project_contributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contributor',
        ),
    ]
