# Generated by Django 3.2.22 on 2023-11-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_name', models.CharField(max_length=80, unique=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
