# Generated by Django 3.2.22 on 2023-11-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0003_auto_20231103_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='company',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='country',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='display_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='display_phone_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='display_town_city',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='linkedin_username',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='town_city',
            field=models.CharField(blank=True, max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='work_title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
