# Generated by Django 3.2.22 on 2023-11-03 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0004_auto_20231103_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechUser',
            fields=[
                ('parentuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='custom_account.parentuser')),
            ],
            options={
                'abstract': False,
            },
            bases=('custom_account.parentuser',),
        ),
    ]
