# Generated by Django 3.2.22 on 2023-11-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0005_techuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='techuser',
            name='github_username',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='techuser',
            name='seeking_employment',
            field=models.BooleanField(default=False),
        ),
    ]
